site_name: FabMechanics
repo_url: https://www.makilab.org
repo_name: FabMechanics

nav:
  - Bienvenue: index.md
  - Chapitres:
    - Charnières à rotation: ./parts/hinges/hinges.md
    - Trous et alésages: ./parts/holes/holes.md
theme:
  name: material
  features:
    - navigation.expand # Pour que le sous-titre reste tjs ouvert

extra:
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:fabmechanics@proton.me
    - icon: fontawesome/brands/github
      link: https://github.com/gixita/fabmechanics
extra_css:
  - style.css
copyright: 'Content under MIT license.'
