site_name: FabMechanics
repo_url: https://www.makilab.org
repo_name: FabMechanics

nav:
  - Bienvenue: index.md
  - Chapitres:
    - Charnières: ./parts/hinges/hinges.md
theme:
  name: material
  features:
    - navigation.expand # Pour que le sous-titre reste tjs ouvert
